@trading_engine_HostAddress = http://localhost:5066

GET {{trading_engine_HostAddress}}/health
Accept: application/json

###

POST {{trading_engine_HostAddress}}/api/signals
Content-Type: application/json

{
  "type": "entry",
  "direction": "SHORT",
  "contracts": 7,
  "stop_loss": 30755.5,
  "take_profit_1": 30709.5,
  "take_profit_2": 30686.25,
  "entry_price": 30736.25,
  "symbol": "MNQ1!"
}

###

GET {{trading_engine_HostAddress}}/api/signals
Accept: application/json

###

GET {{trading_engine_HostAddress}}/api/orders
Accept: application/json

###

GET {{trading_engine_HostAddress}}/api/executions
Accept: application/json

###

GET {{trading_engine_HostAddress}}/api/positions
Accept: application/json

###

POST {{trading_engine_HostAddress}}/api/paper/orders/cancel-working
Content-Type: application/json

{
  "symbol": "MNQ1!"
}

###

POST {{trading_engine_HostAddress}}/api/paper/positions/close
Content-Type: application/json

{
  "symbol": "MNQ1!"
}

###

POST {{trading_engine_HostAddress}}/api/paper/flatten
Content-Type: application/json

{}

###
